# Generated by Django 4.0.4 on 2022-06-18 10:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_review_recommended_alter_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='star_rating',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
